### ISSUE TITLE
Execution is stuck on Ffmpeg.Execute() call

### ISSUE THREAD

**Issue by LluisTrapeCasanovas** [Laerdal/Laerdal.Xamarin.FFmpeg#1]
**Describe the bug**
i try this package in few days but i can't working good, 
First, for installing, not need build, only install git Laerdal.Xamarin.FFmpeg.*** in forms, and install git Laerdal.Xamarin.FFmpeg.android.*** in android projecta, and install Laerdal.Xamarin.FFmpeg.ios.*** in ios project.
Ok we take the external libraries.
in forms i execute FFmpeg.Execute("*****") and encoding the video, but when finish, not stop the process of ffmpeg(i think), and the app is blocked and i don't recive any message of finished/error.

I try too, make dependeces in android and ios projects, but the same problem. the app is blocked.
I try too, make  IExecuteCallback in async into dependence.. now not work(i think i do bad implementation)

Am I a unique person that try this package, and have a problem??
Someone can send instructions for make a good app with this package??
if not work, i don't understand because exist this repository.
My opinion this repository are more interesting, usually i work with ffmpeg in c#

ps. i used a similar reposity in flutter and works very well. but dart not is c#

**Comment by framinosona** [comment]
Hi, this package is not very tested indeed, still work in progress.

I agree with you that it is more interesting to work in C# 🙂

Could you share your code ? 

Ps. This library is a simple contribution to the Open-Source Community. Feel free to contribute to it too and help us make it better for the good of all 🙂

**Comment by LluisTrapeCasanovas** [comment]
Hi,
thanks for answering so quickly.
In all that I can help, I will help.
My first test, execute FFMPeg in forms.
![img0](https://user-images.githubusercontent.com/78168946/106281986-45002b00-6240-11eb-808b-c23e0c3160af.jpg)
all correct, but when finish encode video, the app is block and not go to line of Console.WriteLine.
I was try execute ffmpeg.Execute in thread, the same problem, the app blocked.(i understend, in thred only blocked the thread)
If uses dependecies in android project, and execute ffmpeg.execute without async method, has the same behavior

**Comment by framinosona** [comment]
Okay I see. The ffmpeg is an attempt to have both the ios and Android packages in one. Could you try to use only the Android nuget in your Xamarin.Android project. Same for ios? I've tested the " -h" command on both ad they work well.
Also I've just pushed a new version of the shared ffmpeg nuget, could you try to use it.

So : 
- using Laerdal.Xamarin.Ffmpeg.Android nuget and namespace in a Xamarin Android ONLY  project.

- using Laerdal.Xamarin.Ffmpeg.iOS nuget and namespace in a Xamarin iOS ONLY project.

- using Laerdal.Xamarin.Ffmpeg in all project of a Xamarin.Forms project

**Comment by LluisTrapeCasanovas** [comment]
In ios i dont try test, today i was intall vs2019 in my mini turtle mac(2010). Tomorrow i will do test in iphone 6, also, i will make the projects how you said. i Don't try with only android project.

today i was try with executeasync in xamarin.forms in android project, but i have problems with create IExecuteCallback.

i made a class->
class callbacks : Java.Lang.Object, IExecuteCallback......

but i recibe error  handler must be valid, i think is for Java.Lang.Object, i try JNIEnv.FindClass with names of register, but i dont luky. i dont know how implement. but, i recive value in SetJniIdentityHashCode function.

**Comment by LluisTrapeCasanovas** [comment]
Test Xamarin.Android (only project android) ->FFmpeg.execute() same problem, encoder video and save in device, but when finish blocking the app.
ps. i use Task.run in this example, while encoding, the app work good.
Task.Run(() => { 
      int i = FFmpeg.Execute(cmd);
      System.Console.WriteLine(i);
  });


I use android 11.0.

**Comment by framinosona** [comment]
Okay good to know, maybe it is supposed to be used like that. In my sample it executes on click of a button, maybe this is why I don't have any problem because it created a thread of his own

**Comment by LluisTrapeCasanovas** [comment]
Test ios -> work perfect, encoding video and send mesage when finish.

**Comment by LluisTrapeCasanovas** [comment]
test forms->Now work ffmpeg , but in android continous with problem. when finish encoding video, blocked app. 
I searching trace file for find error, but i dont find the file.....

**Comment by LluisTrapeCasanovas** [comment]
i do new test, i try the app in android in release mode and work good!!! the problem is in debug mode, for some reason, the app crashes, but in release, works very good.
I don't know if this problem have solution.

It would be interesting how to use callback in android and ios.

**Comment by framinosona** [comment]
Oh that's awesome informations ! Thank-you  for all the tests! Okay I think I know what to look for. I'm on weekend but I will look at it on Monday 🙂

**Comment by LluisTrapeCasanovas** [comment]
Thanks for your big job.

**Comment by j2bmw** [comment]
I have a similar issue with converting video files in a Xamarin forms project. On Android app, it locks the app inside Visual Studio debugger. However, the conversion seems completed (at least a significant portion is done and can be played back) outside the debugger without locking device. The bigger problem: after the conversion, the app crashes not long after. Please see the device log "crash after converting to mp4.txt" [crash after converting to mp4.txt](https://github.com/Laerdal/Laerdal.Xamarin.FFmpeg/files/5971433/crash.after.converting.to.mp4.txt). It seems the conversion didn't complete and it triggered the following exception:
02-12 19:04:18.635 Google Pixel 3 Error 23366 libc Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 23470 (x.tecommobilev2), pid 23366 (x.tecommobilev2)
02-12 19:04:18.624 Google Pixel 3 Error 23366 libc FORTIFY: pthread_mutex_lock called on a destroyed mutex (0x77f6994c30)

It seems this crash is related to int rc = FFmpeg.Execute($"-i \"{filename}\" \"{mp4File}\"");

If I comment out this line, there is no crash. I haven't figured out the cause. 

I tried the alternative using long rc = Laerdal.Xamarin.FFmpeg.Android.FFmpeg.ExecuteAsync($"-i "{_recordedVideoFileName}" "{mp4File}"", executeCallback);

The issue remains.

**Comment by LluisTrapeCasanovas** [comment]
I find a new problem, but i don't know if the problem is in xamarin or is in ffmpeg.movile. the theme is i extract some frame video to jpg, when finish the extract, i transform image.. but when i transform  some image, the app crash. i think is for a memory.
one time crash app, I turn it on again, and transform saved images, without problem.
i try copy images to other name and make transform, but i have same problem.
I test in xamarin.forms(only android) and xamarin.android. same problem with two plataforms.
i try in debug(blocked when finish ffmpeg) and release mode.
only stop the app, i don't recive any message error and any log error.

ps: i find this line in logcat
E InputDispatcher: channel '85b5288 xxxxxxxxxx/crc643c5e559cd371fef3.MainActivity (server)' ~ Channel is unrecoverably broken and will be disposed!

**Comment by LluisTrapeCasanovas** [comment]
i find a solution for all problems in my project, i use this line FFmpegConfig.IgnoreSignal(24);
//24(Com.Arthenica.Mobileffmpeg.Signal.Sigxcpu)
my app can debug ffmpeg time and solution works after use ffmpeg function
